version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/web
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
